### ISSUE TITLE
Phoenix Join Error

### ISSUE THREAD

**Issue by WeliAn** [DSCLAB/phoenix#2]
只要 select SQL 有做 join, 且 where 條件，查詢的 endtmst 起始時間在
 > 2015-09-03 21:55:00.000 之後，就會立即返回以下錯誤： 
java.lang.RuntimeException: org.apache.phoenix.exception.PhoenixIOException: org.apache.phoenix.exception.PhoenixIOException: org.apache.hadoop.hbase.DoNotRetryIOException: Could not find hash cache for joinId: m�3��'��. The cache might have expired and have been removed. 

例如：
1.  select a.*, b.server_name from fdc.fdc_run_data a, fdc.file_server_info b where endtmst = to_date('2015-09-03 21:55:00.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and b.is_primary = true and a.server = b.server_id ; 
2.  select a.*, b.server_name from fdc.fdc_run_data a, fdc.file_server_info b where endtmst >= to_date('2015-09-03 21:55:00.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and endtmst < to_date('2015-09-04 21:55:02.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and b.is_primary = true and a.server = b.server_id ;
這兩個是可以成功的。 

1.  select a.*, b.server_name from fdc.fdc_run_data a, fdc.file_server_info b where endtmst = to_date('2015-09-03 21:55:01.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and b.is_primary = true and a.server = b.server_id ; 
2.  select a.*, b.server_name from fdc.fdc_run_data a, fdc.file_server_info b where endtmst >= to_date('2015-09-03 21:55:01.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and endtmst < to_date('2015-09-03 21:55:04.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and b.is_primary = true and a.server = b.server_id ; 
3.  select a.*, b.server_name from fdc.fdc_run_data a, fdc.file_server_info b where endtmst >= to_date('2015-09-03 22:55:00.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and endtmst < to_date('2015-09-03 22:55:04.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and b.is_primary = true and a.server = b.server_id ;
這個三個則會失敗。

但單純select一個表格是可以的。
1.  select * from fdc.fdc_run_data where endtmst = to_date('2015-09-03 21:55:01.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') 
2.  select * from fdc.fdc_run_data where endtmst >= to_date('2015-09-03 21:55:01.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and endtmst < to_date('2015-09-03 21:55:04.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') 
3.  select * from fdc.fdc_run_data where endtmst >= to_date('2015-09-03 22:55:00.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') and endtmst < to_date('2015-09-03 22:55:04.000', 'yyyy-MM-dd HH:mm:ss.SSS', 'local') 

ps.在測試環境下是沒有問題的，正式環境才有以上問題。

**Comment by chia7712** [comment]
resolved. see https://github.com/chia7712/phoenix-4.4.0/commit/c3b722283319b6d255552da4a52744592346a979
